### PR TITLE
Fixed - avoid_print rule fails to catch tear-off usage

### LINKED ISSUE #1696: avoid_print fails to catch tear-off usage
Example:

```dart
Future.value('hello').then(print);
```

If the `avoid_print` rule is on, no lint warning is raised.

### PR DESCRIPTION
**Pull request by jawahars16**
The lint rule `avoid_print` is not catching the scenario when `print` function passed as an argument. This PR includes code that added additional check to validate function arguments for `print`.

Fixes #1696

### CODE REVIEW

File: lib/src/rules/avoid_print.dart [hunk 1]
```diff
@@ -41,6 +42,17 @@ class _Visitor extends SimpleAstVisitor {
 
   _Visitor(this.rule);
 
+  _validateArgument(Expression expression) {
+    if (expression is SimpleIdentifier) {
+      final Element element = expression.staticElement;
+      if (element is FunctionElement &&
+          element?.name == 'print' &&
+          element?.library?.name == 'dart.core') {
```
Comment (pq) [inline lib/src/rules/avoid_print.dart]: perhaps: `element.libary.isDartCore`?

File: lib/src/rules/avoid_print.dart [hunk 2]
```diff
@@ -41,6 +42,17 @@ class _Visitor extends SimpleAstVisitor {
 
   _Visitor(this.rule);
 
+  _validateArgument(Expression expression) {
+    if (expression is SimpleIdentifier) {
+      final Element element = expression.staticElement;
+      if (element is FunctionElement &&
+          element?.name == 'print' &&
```
Comment (pq) [inline lib/src/rules/avoid_print.dart]: since you just verified `element is FunctionElement` I think you can drop the `?`, simplifying this to:

    element.name == 'print'

**Comment by pq** [comment]
Thanks a million for your contributions!

File: lib/src/rules/avoid_print.dart (hunk 1 above)
Comment (jawahars16) [reply lib/src/rules/avoid_print.dart]: Changed to `isDartCore`

File: lib/src/rules/avoid_print.dart (hunk 2 above)
Comment (jawahars16) [reply lib/src/rules/avoid_print.dart]: Removed unwanted null checks.

**Comment by bwilkerson** [comment]
I have no idea why it's failing for your PR, but it's clearly a bug. I'll have a fix out in a minute.

**Comment by bwilkerson** [comment]
PR out for review: https://github.com/dart-lang/linter/pull/1752

**Comment by bwilkerson** [comment]
PR landed.

**Comment by pq** [comment]
Restarting build...

**Comment by pq** [comment]
@jawahars16: thank you!  I'd like to an attribution to `AUTHORS`,

https://github.com/dart-lang/linter/blob/master/AUTHORS

How would you like to appear?

**Comment by jawahars16** [comment]
> @jawahars16: thank you! I'd like to an attribution to `AUTHORS`,
> 
> https://github.com/dart-lang/linter/blob/master/AUTHORS
> 
> How would you like to appear?

Thank you. 😄 

Jawahar <jawahars_16@live.in>
