### PR TITLE
Check for-elements, if-elements, and set-literals for adjacent strings

### LINKED ISSUE #2343: no_adjacent_strings_in_list should trigger when the collection if is missing a trailing comma
**Describe the issue**
no_adjacent_strings_in_list should trigger when the `collection if` is missing a trailing comma.

**To Reproduce**
```
List<String> list = <String>[
  'a',
  'b'
  'c'
];
```
triggers the lint but
```
List<String> list = <String>[
  'a',
  if (true) 'b'
  'c'
];
```
does not.

**Expected behavior**
`Lint warning: DON'T use adjacent strings in list.` on the `if (true) 'b'` line.

**Additional context**
Real world bug:
https://github.com/flutter/flutter/pull/70325/files#diff-fbf1a86439c67e75e90a00f32fd2b789323582ced2f4f5cfea2d27a1af18aa30R427

### PR DESCRIPTION
**Pull request by srawlins**
# Description

Adds for-elements, if-elements, and set literals to the `no_adjacent_strings_in_list` rule.

Fixes #2343 and #2727. This is a replacement for https://github.com/dart-lang/linter/pull/2726 as I don't use that source repo any more.

This is an alternative to https://github.com/dart-lang/linter/pull/3740 (creating a new rule).

### CODE REVIEW

File: lib/src/rules/no_adjacent_strings_in_list.dart [hunk 1]
```diff
@@ -55,6 +58,20 @@ class _Visitor extends SimpleAstVisitor<void> {
...
+  void visitForElement(ForElement node) {
+    if (node.body is AdjacentStrings) {
+      rule.reportLint(node.body);
+    }
+  }
+
+  @override
+  void visitIfElement(IfElement node) {
+    if (node.thenElement is AdjacentStrings) {
+      rule.reportLint(node.thenElement);
```
Comment (bwilkerson) [inline lib/src/rules/no_adjacent_strings_in_list.dart:71]: We probably don't want to report a lint here if there's an `elseElement`, but should report a lint in the `elseElement` if it exists. For example, given
```
var list = [
  if (c) 'a' 'b' else 'c' 'd'
];
```
It wouldn't make any sense to add a comma between `'a'` and `'b'` because `'b' else 'c' 'd'` isn't be a valid expression. But it would name sense to suggest a comma between `'c'` and `'d'`.

File: test_data/rules/no_adjacent_strings_in_list.dart [hunk 2]
```diff
@@ -5,23 +5,45 @@
...
   ];
 
-  List<String> list2 = <String>[
+  var list2 = [
     'a' // LINT
     'b'
     'c'
   ];
+
+  var list3 = [
```
Comment (bwilkerson) [inline test_data/rules/no_adjacent_strings_in_list.dart:20]: Consider using reflective tests for the new tests.

File: lib/src/rules/no_adjacent_strings_in_list.dart (hunk 1 above)
Comment (srawlins) [reply lib/src/rules/no_adjacent_strings_in_list.dart:71]: Great catch! Done.

File: test_data/rules/no_adjacent_strings_in_list.dart (hunk 2 above)
Comment (srawlins) [reply test_data/rules/no_adjacent_strings_in_list.dart:20]: I was thinking it would be more confusing (like, really confusing) to have the test cases split between integration tests and reflective tests.

But I am really on board with moving to reflective tests ASAP.

**Comment by srawlins** [comment]
Sorry for the delay.

Testing in flutter at https://dart-review.googlesource.com/c/sdk/+/277046

**Comment by srawlins** [comment]
This passed flutter analysis. 🎉

File: test_data/rules/no_adjacent_strings_in_list.dart (hunk 2 above)
Comment (bwilkerson) [reply test_data/rules/no_adjacent_strings_in_list.dart:20]: I'm fine with you not changing it, but the reason I said something is that we've been writing new tests as reflective tests so that we don't increase the technical debt in the process of writing new tests. I understand that having both styles is confusing, but I think that not increasing the technical debt is more important.

**Review by bwilkerson — APPROVED** [review]
