### PR TITLE
Fix unnecessary_parenthesis's treatment of function expressions

### LINKED ISSUE #1284: unnecessary_parenthesis requests that an expression-function body unwrap, which breaks the code
Take this code:

```dart
var i = ((b) => b is bool ? b : false)(x);
```

The unnecessary_parenthesis rule warns about the parens here, but removing them breaks the statement.

### PR DESCRIPTION
**Pull request by srawlins**
Fixes #1284 

The new test fails without the change to lib/

### CODE REVIEW

File: test/rules/unnecessary_parenthesis.dart [hunk 1]
```diff
@@ -27,6 +27,7 @@ main() async {
   true ? [] : []..add(''); // OK
   m(p: (1 + 3)); // LINT
   a..b = (c..d); // OK
+  ((x) => x is bool ? x : false)(a); // OK
```
Comment (bwilkerson) [inline test/rules/unnecessary_parenthesis.dart]: What about

(getterReturningFunction)(x);

Comment (srawlins) [reply test/rules/unnecessary_parenthesis.dart]: Great test! Added.
