### PR TITLE
fix local functions in `no_leading_underscores_for_local_identifiers`

### LINKED ISSUE #3360: no_leading_underscores_for_local_identifiers doesn't complain about local functions
The following code does not produce a `no_leading_underscores_for_local_identifiers` lint, even though I would have expected it to complain about `_bar`:

```dart
int foo() {
  int _bar() { // Why no no_leading_underscores_for_local_identifiers lint here?
    return 10;
  }
  return _bar();
}
```

Complaining here would also seem to be in line with "Effective Dart" [1] (emphasize mine):

> There is no concept of “private” for local variables, parameters, **local functions**, or library prefixes. When one of those has a name that starts with an underscore, it sends a confusing signal to the reader. To avoid that, **don’t use leading underscores** in those names.

[1] https://dart.dev/guides/language/effective-dart/style#dont-use-a-leading-underscore-for-identifiers-that-arent-private

### PR DESCRIPTION
**Pull request by pq**
Fixes #3360

/cc @bwilkerson

### CODE REVIEW

File: lib/src/rules/no_leading_underscores_for_local_identifiers.dart [hunk 1]
```diff
@@ -113,6 +114,13 @@ class _Visitor extends SimpleAstVisitor<void> {
     }
   }
 
+  @override
+  void visitFunctionDeclaration(FunctionDeclaration node) {
+    if (node.parent is FunctionDeclarationStatement) {
```
Comment (bwilkerson) [inline lib/src/rules/no_leading_underscores_for_local_identifiers.dart:119]: Consider visiting `FunctionDeclarationStatement` and unconditionally invoking `checkIdentifier(node.functionDeclaration.name)`. It should be more performant because it will avoid a type check.

**Review by bwilkerson — APPROVED** [review]

File: lib/src/rules/no_leading_underscores_for_local_identifiers.dart (hunk 1 above)
Comment (pq) [reply lib/src/rules/no_leading_underscores_for_local_identifiers.dart:119]: Excellent.  Thanks!

File: lib/src/rules/no_leading_underscores_for_local_identifiers.dart [hunk 2]
```diff
@@ -65,6 +65,8 @@ class NoLeadingUnderscoresForLocalIdentifiers extends LintRule
     registry.addDeclaredIdentifier(this, visitor);
     registry.addFormalParameterList(this, visitor);
     registry.addForPartsWithDeclarations(this, visitor);
+    registry.addFunctionDeclaration(this, visitor);
```
Comment (albertms10) [inline lib/src/rules/no_leading_underscores_for_local_identifiers.dart:68]: Could this registry entry be safely removed, as we are not using it?

Comment (pq) [reply lib/src/rules/no_leading_underscores_for_local_identifiers.dart:68]: Oh dear.  Great catch.  Thanks!

https://github.com/dart-lang/linter/pull/3364
