### PR TITLE
Fix iterable_contains_unrelated_type

### LINKED ISSUE #1003: iterable_contains_unrelated_type not working for List
In IntelliJ, I see this triggers the lint:

```
  Iterable<int> foo = [1];
  print(foo.contains('3'));
```

and this:

```
  Set<int> foo = Set.from([1]);
  print(foo.contains('3'));
```

but not this:

```
  List<int> foo = [1];
  print(foo.contains('3'));
```

I'm at a loss as to why not; it looks like there are test cases that should catch this in the linter code, and they pass. Maybe there is something in the test setup that is now different from the actual `List`?

### PR DESCRIPTION
**Pull request by xvrh**
Fixes #1003

This is an attempt to fix `iterable_contains_unrelated_type`. This rule works in the test suite but not with a real SDK.

This is because the [MockSdk] defines the hierarchy as `List<T> implements Iterable<T>` ([analyzer/mock_sdk.dart](https://github.com/dart-lang/sdk/blob/caa31f55be518e2de0bf723c81c853c2362dafb5/pkg/analyzer/lib/src/test_utilities/mock_sdk.dart#L419)) while the real SDK defines `List<T> extends EfficientLengthIterable<T>` ([sdk/core/list.dart](https://github.com/dart-lang/sdk/blob/c5d01ec4f7078a75b038a2ed04312afb50154323/sdk/lib/core/list.dart#L52))

### CODE REVIEW

File: test/rules/iterable_contains_unrelated_type.dart [hunk 1]
```diff
@@ -151,12 +151,6 @@ abstract class B3 extends A3 {}
 
 bool takesB3(B3 b) => b.contains('a'); // OK
 
-abstract class A2 implements Iterable<String> {}
```
Comment (xvrh) [inline test/rules/iterable_contains_unrelated_type.dart:154]: I remove it because this is the same case as A1 above

**Review by bwilkerson — APPROVED** [review]

**Comment by pq** [comment]
> This is because the [MockSdk] defines the hierarchy as List<T> implements Iterable<T> (analyzer/mock_sdk.dart) while the real SDK defines List<T> extends EfficientLengthIterable<T> (sdk/core/list.dart)

Ah.  That's a problem.

It'd be good to get that updated.  (fyi @scheglov)

**Review by pq — APPROVED** [review]
💎 

Thanks!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/192048
