### PR TITLE
fix `prefer_collection_literals` named typed param false positive

### LINKED ISSUE #2985: prefer_collection_literals and empty named LinkedHashSet
As I want create a empty named LinkedHashSet, the lint https://dart-lang.github.io/linter/lints/prefer_collection_literals.html has a false positive.
Without a named parameter, the linter does not complain.  

```
class Foo {}

void a({required LinkedHashSet<Foo> some}) {}
void b(LinkedHashSet<Foo> some) {}

void c() {
  a(some: LinkedHashSet()); // lint false positive
  b( LinkedHashSet()); // no lint
}
```

### PR DESCRIPTION
**Pull request by pq**
Fixes #2985

/cc @bwilkerson

### CODE REVIEW

File: test/rules/prefer_collection_literals.dart [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+    
+class Foo {}
+
+void a({required LinkedHashSet<Foo> some}) {}
+
+void c() {
+  a(some: LinkedHashSet<Foo>());
+}
+''', [
+      // No lints
```
Comment (bwilkerson) [inline test/rules/prefer_collection_literals.dart:33]: Not related to this PR, and it might be more confusing, but consider making the list of diagnostics optional so that we don't have to have an explicit list in every "no diagnostics" call.

File: test/rules/prefer_collection_literals.dart [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+    
+class Foo {}
+
+void a({required Set<Foo> some}) {}
+
+void c() {
+  a(some: LinkedHashSet<Foo>());
+}
+''', [
+      lint('prefer_collection_literals', 103, 20),
```
Comment (bwilkerson) [inline test/rules/prefer_collection_literals.dart:49]: Consider shortening this slightly, and removing duplication, by writing `lint(lintRule, 103, 20);`. Not sure it's better.

**Review by bwilkerson — APPROVED** [review]

File: test/rules/prefer_collection_literals.dart (hunk 1 above)
Comment (pq) [reply test/rules/prefer_collection_literals.dart:33]: Interesting.  Alternatively how about a new `assertNoDiagnostics`?

File: test/rules/prefer_collection_literals.dart (hunk 2 above)
Comment (pq) [reply test/rules/prefer_collection_literals.dart:49]: I'm not sure either.  I'll add this to a list of things to discuss offline.

**Comment by pq** [comment]
Thanks!


(I'll address the analyzer API changes in another PR.)

File: test/rules/prefer_collection_literals.dart (hunk 1 above)
Comment (bwilkerson) [reply test/rules/prefer_collection_literals.dart:33]: I like that better than making it optional. Less error prone.

**Comment by pq** [comment]
Ha.  Of course Konstantin already got to it: https://github.com/dart-lang/linter/pull/2989. 😄
