### PR TITLE
fix null type access

### LINKED ISSUE #1939: NoSuchMethodError: The getter 'isDartCoreBool' was called on null from unrelated_type_equality_checks.dart:180
From `2.8.288454792-edge+google3-v2`:

```
NoSuchMethodError: The getter 'isDartCoreBool' was called on null.
Receiver: null
Tried calling: isDartCoreBool
	at Object.noSuchMethod	(dart:core )
	at _Visitor.visitBinaryExpression	(unrelated_type_equality_checks.dart:180 )
	at BinaryExpressionImpl.accept	(ast.dart:967 )
	at LinterVisitor._runSubscriptions	(linter_visitor.dart:725 )
	at LinterVisitor.visitBinaryExpression	(linter_visitor.dart:59 )
	at BinaryExpressionImpl.accept	(ast.dart:967 )
	at NodeListImpl.accept	(ast.dart:7520 )
	at ArgumentListImpl.visitChildren	(ast.dart:363 )
	at RecursiveAstVisitor.visitArgumentList	(visitor.dart:623 )
	at ArgumentListImpl.accept	(ast.dart:359 )
	at MethodInvocationImpl.visitChildren	(ast.dart:7090 )
	at RecursiveAstVisitor.visitMethodInvocation	(visitor.dart:1067 )
	at LinterVisitor.visitMethodInvocation	(linter_visitor.dart:468 )
	at MethodInvocationImpl.accept	(ast.dart:7083 )
	at ConstructorFieldInitializerImpl.visitChildren	(ast.dart:2652 )
	at RecursiveAstVisitor.visitConstructorFieldInitializer	(visitor.dart:749 )
	at LinterVisitor.visitConstructorFieldInitializer	(linter_visitor.dart:150 )
	at ConstructorFieldInitializerImpl.accept	(ast.dart:2647 )
	at NodeListImpl.accept	(ast.dart:7520 )
	at ConstructorDeclarationImpl.visitChildren	(ast.dart:2570 )
	at RecursiveAstVisitor.visitConstructorDeclaration	(visitor.dart:743 )
	at LinterVisitor.visitConstructorDeclaration	(linter_visitor.dart:144 )
	at ConstructorDeclarationImpl.accept	(ast.dart:2562 )
	at NodeListImpl.accept	(ast.dart:7520 )
	at ClassDeclarationImpl.visitChildren	(ast.dart:1549 )
	at RecursiveAstVisitor.visitClassDeclaration	(visitor.dart:701 )
	at LinterVisitor.visitClassDeclaration	(linter_visitor.dart:102 )
	at ClassDeclarationImpl.accept	(ast.dart:1519 )
	at NodeListImpl.accept	(ast.dart:7520 )
	at CompilationUnitImpl.visitChildren	(ast.dart:2102 )
	at RecursiveAstVisitor.visitCompilationUnit	(visitor.dart:725 )
	at LinterVisitor.visitCompilationUnit	(linter_visitor.dart:126 )
	at CompilationUnitImpl.accept	(ast.dart:2095 )
	at LibraryAnalyzer._computeLints	(library_analyzer.dart:357 )
	at LibraryAnalyzer.analyzeSync.<fn>	(library_analyzer.dart:198 )
	at _PerformanceTagImpl.makeCurrentWhile	(utilities_general.dart:256 )
	at LibraryAnalyzer.analyzeSync	(library_analyzer.dart:193 )
	at LibraryAnalyzer.analyze.<fn>	(library_analyzer.dart:123 )
	at _PerformanceTagImpl.makeCurrentWhile	(utilities_general.dart:256 )
	at LibraryAnalyzer.analyze	(library_analyzer.dart:122 )
	at AnalysisDriver._computeAnalysisResult.<fn>	(driver.dart:1278 )
	at PerformanceLog.run	(performance_logger.dart:34 )
	at AnalysisDriver._computeAnalysisResult	(driver.dart:1254 )
	at AnalysisDriver.performWork	(driver.dart:932 )
	at <asynchronous gap>	(async )
	at AnalysisDriverScheduler._run	(driver.dart:1979 )
	at <asynchronous gap>	(async )
	at AnalysisDriverScheduler.start	(driver.dart:1913 )
	at SocketServer.createAnalysisServer	(socket_server.dart:87 )
	at StdioAnalysisServer.serveStdio	(stdio_server.dart:41 )
	at Driver.startAnalysisServer.<fn>	(driver.dart:606 )
	at runZoned	(dart:async )
	at Driver._captureExceptions	(driver.dart:721 )
	at Driver.startAnalysisServer	(driver.dart:604 )
	at Driver.start	(driver.dart:504 )
	at main	(server.dart:40 )
	at _AsyncAwaitCompleter.start	(dart:async )
	at main	(server.dart:29 )
```

### PR DESCRIPTION
**Pull request by pq**
Fixes #1939

/cc @bwilkerson

### CODE REVIEW

File: lib/src/rules/unrelated_type_equality_checks.dart [hunk 1]
```diff
@@ -177,8 +177,9 @@ class _Visitor extends SimpleAstVisitor<void> {
 
   @override
   void visitBinaryExpression(BinaryExpression node) {
-    final isDartCoreBoolean = node.staticType.isDartCoreBool;
-    if (!isDartCoreBoolean ||
+    final isDartCoreBoolean = node.staticType?.isDartCoreBool;
+    if (isDartCoreBoolean == null ||
+        !isDartCoreBoolean ||
```
Comment (bwilkerson) [inline lib/src/rules/unrelated_type_equality_checks.dart]: For NNBD, I suspect we'll want to change this to
```
final isDartCoreBoolean = node.staticType?.isDartCoreBool ?? false;
  if (!isDartCoreBoolean ||
```
Otherwise, I think line 182 will have to read `!isDartCoreBoolean!`, which, while nicely emphatic, is a bit much.

Comment (pq) [reply lib/src/rules/unrelated_type_equality_checks.dart]: Haha.  Thanks!
