### PR TITLE
don't report `unnecessary_parenthesis` for null-aware cascades

### LINKED ISSUE #4041: `unnecessary_parenthesis` false positive with null-aware + cascade + assignment
False positive for this case:
```dart
class Foo {
  var bar = false;
  void method() {}
}

void testLint(Foo? foo) {
  (foo?..bar = true)?.method();    // Unnecessary use of parentheses.
}
```

Wrong fix that is being suggested:
```dart
void testLint(Foo? foo) {
  foo?.bar = true.method();
}
```

### PR DESCRIPTION
**Pull request by pq**
Fixes #4041

/cc @bwilkerson

### CODE REVIEW

**Review by bwilkerson — APPROVED** [review]

**Comment by bwilkerson** [comment]
See also https://github.com/dart-lang/linter/pull/4042

File: lib/src/rules/unnecessary_parenthesis.dart [hunk 1]
```diff
@@ -96,6 +96,7 @@ class _Visitor extends SimpleAstVisitor<void> {
           return;
         }
       } else if (parent is MethodInvocation) {
+        if (expression is CascadeExpression) return;
```
Comment (asashour) [inline lib/src/rules/unnecessary_parenthesis.dart:99]: This condition can be moved to the root of the method, in this case, there is a second check (in line 150 now), which should be removed.

Another solution is to use the implementation of the other PR.

Comment (pq) [reply lib/src/rules/unnecessary_parenthesis.dart:99]: Ah!  This check here is scoped to just the null aware and simple identifier cases so I'm not sure it's identical to the check in 150 but I'm sure you're right that this could be tidied up.  (Lots of special cases here...)

Feel free to follow-up w/ any refinements?  It'd be great to flesh out the tests too.  (FYI @oprypin who may have more cases to consider.)
