### PR TITLE
Fix false positive in `use_rethrow_when_possible`

### LINKED ISSUE #2789: False positive for `use_rethrow_when_possible`
* Dart SDK Version: 2.13

At the moment, `rethrow` is prohibited in ternary expressions. However, the normal `throw` equivalent is allowed. To make matters interesting, `dart analyzer` emits a [`use_rethrow_when_possible`](https://dart-lang.github.io/linter/lints/use_rethrow_when_possible.html)  hint for the normal `throw` equivalent even though the suggested fix isn't valid in this context.

```dart
try {
  // do something
} on SomeError catch (e) {
  e.code == Code.something ? handle() : rethrow; // Fails to compile with "'rethrow' can't be used as an identifier because it's a keyword."
}

try {
// do something
} on SomeError catch (e) {
  e.code == Code.something ? handle() : throw e; // Compiles but dart_analyzer emits a "use_rethrow_when_possible" hint
}
```

In my opinion, this interaction is quite misleading and it would be nice if either `rethrow` is allowed in ternary expressions or `dart_analyzer` does not flag `throw e` in this context.

### PR DESCRIPTION
**Pull request by asashour**
Fixes #2789

I don't know how to have a compilable case with `return i ?? throw e;`

### CODE REVIEW

File: lib/src/rules/use_rethrow_when_possible.dart [hunk 1]
```diff
@@ -62,6 +62,8 @@ class _Visitor extends SimpleAstVisitor<void> {
 
   @override
   void visitThrowExpression(ThrowExpression node) {
+    if (node.parent is ConditionalExpression) return;
```
Comment (bwilkerson) [inline lib/src/rules/use_rethrow_when_possible.dart:65]: Should this just be `is Expression`? Consider
```
try {
} catch (e) {
  o.m(throw e);
}
```
It's poor code, but I believe that this would also be a false positive.

Comment (asashour) [reply lib/src/rules/use_rethrow_when_possible.dart]: Oh! I never thought this could even be possible.

Thanks for hinting.

**Review by bwilkerson — APPROVED** [review]

**Review by pq — APPROVED** [review]
👍 Thanks!
