### PR TITLE
fix false positive in `avoid_null_checks_in_equality_operators` w/ non-nullable param

### LINKED ISSUE #2864: remove `avoid_null_checks_in_equality_operators` lints redundant w/ NNBD diagnostics
For example:

```dart
class Person {
  final String name = '';

  @override
  operator ==(other) {
    return other != null &&
          other is Person &&
          name == other.name;
  }
}
```

produces a lint in addition to a `UNNECESSARY_NULL_COMPARISON_FALSE` (which alone should be sufficient).

See: https://dart-review.googlesource.com/c/sdk/+/209661 for more context.

### PR DESCRIPTION
**Pull request by pq**
Fixes #2864

/cc @bwilkerson

### CODE REVIEW

File: lib/src/rules/avoid_null_checks_in_equality_operators.dart [hunk 1]
```diff
@@ -82,34 +84,48 @@ class AvoidNullChecksInEqualityOperators extends LintRule {
...
-      DartTypeUtilities.traverseNodesInDFS(node.body)
-          .where(checkIfParameterIsNull)
-          .forEach(rule.reportLint);
+
+    if (node.name.token.type != TokenType.EQ_EQ || parameters.length != 1) {
+      return;
+    }
+
+    var parameter = DartTypeUtilities.getCanonicalElementFromIdentifier(
+        parameters.first.identifier);
```
Comment (bwilkerson) [inline lib/src/rules/avoid_null_checks_in_equality_operators.dart:111]: I don't understand why we're not just using `parameter.first.declaredElement`. Is there some case that I'm missing?

**Review by bwilkerson — APPROVED** [review]

File: lib/src/rules/avoid_null_checks_in_equality_operators.dart (hunk 1 above)
Comment (pq) [reply lib/src/rules/avoid_null_checks_in_equality_operators.dart:111]: I'm not at all sure.  I notice a comment in `getCanonicalElement` with a bug reference that might be a hint?

```
        // A field element defined in a parameterized type where the values of
        // the type parameters are known.
        //
        // This concept should be invisible when comparing FieldElements, but a
        // bug in the analyzer causes FieldElements to not evaluate as
        // equivalent to equivalent FieldMembers. See
        // https://github.com/dart-lang/sdk/issues/35343.
```

It'd be worth tracking this down (but note that it's called in a bunch of places so we'd want to proceed with some extra caution).

Comment (bwilkerson) [reply lib/src/rules/avoid_null_checks_in_equality_operators.dart:111]: I added a question to the issue to double check, but I believe that `Element.declaration` should replace the need to check for `Member`s.
