### PR TITLE
prefer_constructors_over_static_methods: take generics into account

### LINKED ISSUE #2149: Incorrect prefer_constructors_over_static_methods warning
Consider:

```dart
class Foo {
  Foo._();

  static Foo bar<T>(T value) => Foo._();

  Foo.bar2<T>(T value);
}
```

The static method results in:
`Prefer defining constructors instead of static methods to create instances. (prefer_constructors_over_static_methods`

However, it is not possible to create a constructor with a type parameter.

Dart 2.7.0

### PR DESCRIPTION
**Pull request by srawlins**
# Description

Compare the method's return _type_ with it's parent class's _type_ rather than
comparing _elements_ to account for generics (don't report a method which
returns `A<int>`).

And don't report any generic method, because it might use the type parameters
in its parameters, which a constructor cannot do.

Fixes #2149

### CODE REVIEW

File: lib/src/rules/prefer_constructors_over_static_methods.dart [hunk 1]
```diff
@@ -78,10 +78,12 @@ class _Visitor extends SimpleAstVisitor<void> {
   void visitMethodDeclaration(MethodDeclaration node) {
     final returnType = node.returnType?.type;
     final parent = node.parent;
+    final typeParameters = node.typeParameters?.typeParameters ?? [];
     if (node.isStatic &&
         parent is ClassOrMixinDeclaration &&
         returnType is InterfaceType &&
-        returnType.element == parent.declaredElement &&
+        returnType == parent.declaredElement.thisType &&
```
Comment (bwilkerson) [inline lib/src/rules/prefer_constructors_over_static_methods.dart:85]: If I'm understanding this correctly, this line will be true only when `parent` has no type parameters (isn't generic), so this effectively disables the lint for generic classes. I have to wonder, though whether it might be more clear to future readers to simply ask whether the class declaration has type parameters (`parent.typeParameters != null`).

File: lib/src/rules/prefer_constructors_over_static_methods.dart [hunk 2]
```diff
@@ -78,10 +78,12 @@ class _Visitor extends SimpleAstVisitor<void> {
...
+        typeParameters.isEmpty &&
```
Comment (bwilkerson) [inline lib/src/rules/prefer_constructors_over_static_methods.dart:86]: Rather than create an empty list for every non-generic method, consider dropping line 81 and using `node.typeParameters != null` here instead. (I don't think we need to guard against a malformed declaration in which there is an empty list of type parameters.)

**Review by bwilkerson — APPROVED** [review]

File: lib/src/rules/prefer_constructors_over_static_methods.dart (hunk 2 above)
Comment (srawlins) [reply lib/src/rules/prefer_constructors_over_static_methods.dart:86]: Haha definitely simpler. Thanks

File: lib/src/rules/prefer_constructors_over_static_methods.dart (hunk 1 above)
Comment (srawlins) [reply lib/src/rules/prefer_constructors_over_static_methods.dart:85]: Done
