### PR TITLE
fix false positive in `unnecessary_string_interpolations` w/ nullable interpolated strings

### LINKED ISSUE #2658: false positive in `unnecessary_string_interpolations` with nullable strings
From the analyzer code base:

```dart
class _PSNode implements PSNode {
  @override
  final String? text;
  @override
  String toString() => '$text'; // <= LINT (but not safe to remove)
}

```

### PR DESCRIPTION
**Pull request by pq**
Fixes #2658

/cc @bwilkerson

### CODE REVIEW

File: lib/src/rules/unnecessary_string_interpolations.dart [hunk 1]
```diff
@@ -57,7 +58,9 @@ class _Visitor extends SimpleAstVisitor<void> {
       var end = node.elements[2] as InterpolationString;
       if (start.value.isEmpty && end.value.isEmpty) {
         var staticType = interpolation.expression.staticType;
-        if (staticType != null && staticType.isDartCoreString) {
+        if (staticType != null &&
+            staticType.isDartCoreString &&
+            staticType.nullabilitySuffix != NullabilitySuffix.question) {
```
Comment (bwilkerson) [inline lib/src/rules/unnecessary_string_interpolations.dart:63]: What do we want the behavior to be if the type is `*`, meaning that it comes from a legacy library? Should we continue to lint it even though it might be nullable?

**Review by bwilkerson — APPROVED** [review]

File: lib/src/rules/unnecessary_string_interpolations.dart (hunk 1 above)
Comment (pq) [reply lib/src/rules/unnecessary_string_interpolations.dart:63]: My gut is that we do want to lint it but I'm really not sure.  It'll be interesting to see if this comes up in practice?
