### PR TITLE
fix curly_braces_in_flow_control_structures

### LINKED ISSUE #1548: curly_braces_in_flow_control_structures isn't catching all cases
In the following code, only the last block complains with `curly_braces_in_flow_control_structures`:

Screenshot 2019-05-06 at 5 20 57 pm

Code is here:

https://github.com/flutter/devtools/blob/9bcab46e323c867664e90ee4954ff57ae507a44b/packages/devtools/lib/src/ui/analytics.dart#L280

Even if I fix the last one, it doesn't warn on the other cases:

Screenshot 2019-05-06 at 5 21 44 pm

### PR DESCRIPTION
**Pull request by a14n**
Fixes #1548

### CODE REVIEW

File: lib/src/rules/curly_braces_in_flow_control_structures.dart [hunk 1]
```diff
@@ -86,17 +86,22 @@ class _Visitor extends SimpleAstVisitor {
...
       if (unit.lineInfo.getLocation(node.rightParenthesis.end).lineNumber !=
           unit.lineInfo.getLocation(node.thenStatement.end).lineNumber) {
         rule.reportLint(node.thenStatement);
       }
-    } else if (node.elseStatement is! IfStatement) {
+    } else {
       _check(node.thenStatement);
-      _check(node.elseStatement);
+      if (elseStatement is IfStatement) {
+        _check(elseStatement.thenStatement);
```
Comment (bwilkerson) [inline lib/src/rules/curly_braces_in_flow_control_structures.dart]: If `elseStatement` is an if statement, then I believe we will end up checking the then statement twice: once here and once when `visitIfStatement` is invoked with `elseStatement` as the argument. I think this just wants to be
```
if (elseStatement is! IfStatement) {
  _check(elseStatement);
}
```

Comment (a14n) [reply lib/src/rules/curly_braces_in_flow_control_structures.dart]: yes the elseStatement is checked twice but it's not the same check. Actually the `if (elseStatement == null)` should also check if `node.parent` is a IfStatement to avoid this case.

Comment (bwilkerson) [reply lib/src/rules/curly_braces_in_flow_control_structures.dart]: It wasn't the else statement I was concerned about. Consider the following code:
```dart
if (condA)
  stmtA;
else if (condB)
  stmtB;
else
  stmtC;
```
When this visit method is visiting the if whose condition is `condA` the else statement will not be null, so it will invoke `_check` on `stmtA` (line 101). Because the else statement is another if statement (the one whose condition is `condB`), it will then check that if statement's then statement, which is `stmtB`.

Later, when this visit method is visiting the if statement whose condition is `condB`, it will invoke `_check` on `stmtB` (line 101).

Comment (a14n) [reply lib/src/rules/curly_braces_in_flow_control_structures.dart]: You're right. Thanks. Updated.

File: lib/src/rules/curly_braces_in_flow_control_structures.dart [hunk 2]
```diff
@@ -86,17 +86,22 @@ class _Visitor extends SimpleAstVisitor {
 
   @override
   void visitIfStatement(IfStatement node) {
-    if (node.elseStatement == null) {
+    var elseStatement = node.elseStatement;
+    var parent = node.parent;
+    if (elseStatement == null &&
+        !(parent is IfStatement && parent.elseStatement == node)) {
```
Comment (bwilkerson) [inline lib/src/rules/curly_braces_in_flow_control_structures.dart]: I think this condition can (and maybe should) be removed. I believe it was attempting to guard against a case that can no longer occur.

**Comment by bwilkerson** [comment]
@a14n @pq Does this impact Flutter? If so, we might want to run this over Flutter and fix any new lints before we commit it so that it doesn't block us from rolling a new version of the linter into the sdk. It might also have implications for rolling internally.

**Comment by pq** [comment]
@bwilkerson: I was going to ask the same thing.  I won't have time to do this today (or maybe tomorrow) but happy to look later this week, unless you can in the meantime @a14n?

As always, thanks for your contributions!  💎

**Comment by a14n** [comment]
`curly_braces_in_flow_control_structures` is not currently activated. It could change with flutter/flutter#31448
