### PR TITLE
Fix unnecessary_final: don't fire for fields.

### LINKED ISSUE #1952: `unnecessary_final` false positives
`unnecessary_final` fires for final fields, which is not intended. I'll send a fix.

### PR DESCRIPTION
**Pull request by davidmorgan**
Fixes #1952

### CODE REVIEW

File: lib/src/rules/unnecessary_final.dart [hunk 1]
```diff
@@ -85,9 +85,9 @@ class _Visitor extends SimpleAstVisitor<void> {
   }
 
   @override
-  void visitVariableDeclaration(VariableDeclaration node) {
-    if (node.isFinal) {
-      rule.reportLint(node.name);
+  void visitVariableDeclarationStatement(VariableDeclarationStatement node) {
+    if (node.variables.isFinal) {
+      rule.reportLint(node.variables);
```
Comment (bwilkerson) [inline lib/src/rules/unnecessary_final.dart]: Unlike the previous implementation, this has the potential of highlighting a significantly long range of characters. Consider changing this (and other places the lint is reported for the sake of consistency) to only highlight the keyword `final`.
