### PR TITLE
prefer_function_declarations_over_variables: only final declarations or unmutatated vars

### LINKED ISSUE #823: prefer_function_declarations_over_variables should only lint final elements
otherwise you can not change the value of the variable

```dart
var f = () => true; // LINT
f = () => false;
```

 and the change leads to error:

```dart
f() => true; // OK
f = () => false; // ERROR
```

### PR DESCRIPTION
**Pull request by a14n**
Fixes #823

### CODE REVIEW

File: lib/src/rules/prefer_function_declarations_over_variables.dart [hunk 1]
```diff
@@ -53,8 +53,12 @@ class _Visitor extends SimpleAstVisitor {
 
   @override
   visitVariableDeclaration(VariableDeclaration node) {
-    if (node.initializer != null && node.initializer is FunctionExpression) {
-      rule.reportLint(node);
+    if (node?.initializer is FunctionExpression) {
```
Comment (bwilkerson) [inline lib/src/rules/prefer_function_declarations_over_variables.dart]: nit: I don't think the `node` can be `null`, so the `?.` shouldn't be needed.

Comment (a14n) [reply lib/src/rules/prefer_function_declarations_over_variables.dart]: done
